source 'https://rubygems.org'

gem 'zendesk_api'
gem 'algoliasearch'
# See PR #20 on htmlentities
# https://github.com/threedaymonk/htmlentities/pull/22
gem 'htmlentities', github: 'Jerskouille/htmlentities'
