#! /usr/bin/env ruby

require './crawler.rb'

crawler = Crawler.new
crawler.crawl :sections
crawler.crawl :articles

crawler.index :articles, localized: true, with_slave: true
crawler.index :articles, localized: true, publicly: true
crawler.index :sections, localized: true, publicly: true
