require_relative './types/category.rb'
require_relative './types/user_segment.rb'
require_relative './types/section.rb'
require_relative './types/article.rb'
require_relative './types/topic.rb'
require_relative './types/post.rb'
require_relative './types/user.rb'
