# Site settings
title: Algolia for Zendesk
description: Algolia search inside your Zendesk Help Center
baseurl: "/zendesk" # the subpath of your site, e.g. /blog/
twitter_username: algolia
github_username: algolia
host: 0.0.0.0

# Navigation
navigation:
 - text: Documentation
   url: /documentation/
 - text: About
   url: /about/

# Build settings
markdown: kramdown
kramdown:
  input: GFM

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - headers
  - README.md

# Assets
sass:
  sass_dir: css
